# Generated by Django 4.1.5 on 2023-02-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='face_encodings',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
