# Generated by Django 4.1.5 on 2023-02-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='face_encodings',
            field=models.TextField(default='0,0,0,0,0,0,0,0'),
        ),
    ]
