# Generated by Django 4.1.5 on 2023-02-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_user_image_user_face_encodings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='face_encodings',
            field=models.TextField(default=None, null=True),
        ),
    ]
