# Generated by Django 4.1.5 on 2023-02-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_face_encodings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='face_encodings',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
